library(boot)
library(ggplot2)
library(ggpubr)
library(deeptime)
library(imputeTS)

europe <- read.csv("Europe brachydonts.csv")
balkanotolia <- read.csv("Balkanotolia brachydonts.csv")
centralasia <- read.csv("Central Asia brachydonts.csv")
india <- read.csv("Indian Subcontinent brachydonts.csv")
eastafrica <- read.csv("Eastern Africa brachydonts.csv")
northam <- read.csv("North America brachydonts.csv")
southam <- read.csv("South America brachydonts.csv")

#Function to use with boot
maxbrach <- function(data, indices){
  d <- data[indices,] 
  fit <- max(d$Brachydonts)
  return(fit)
} 

#Create the sliding bins for each 2My interval, conduct the bootstrapping, extract the maxima, mean and BCa 95% confidence intervals for each region
#Where bins only have one point, CIs are manually input
#Europe
eur.1 <- subset(europe,europe$Age >= 32 & europe$Age < 34)
boot.eur.1 <- boot(data=eur.1,statistic=maxbrach,R=10000)
boot.eur.1cis <- boot.ci(boot.eur.1,type="bca")
eur.boot1.stats <- c(33,max(boot.eur.1$t),mean(boot.eur.1$t),boot.eur.1cis$bca[4],boot.eur.1cis$bca[5])
eur.2 <- subset(europe,europe$Age >= 31 & europe$Age < 33)
boot.eur.2 <- boot(data=eur.2,statistic=maxbrach,R=10000)
boot.eur.2cis <- boot.ci(boot.eur.2,type="bca")
eur.boot2.stats <- c(32,max(boot.eur.2$t),mean(boot.eur.2$t),boot.eur.2cis$bca[4],boot.eur.2cis$bca[5])
eur.3 <- subset(europe,europe$Age >= 30 & europe$Age < 32)
boot.eur.3 <- boot(data=eur.3,statistic=maxbrach,R=10000)
boot.eur.3cis <- boot.ci(boot.eur.3,type="bca")
eur.boot3.stats <- c(31,max(boot.eur.3$t),mean(boot.eur.3$t),boot.eur.3cis$bca[4],boot.eur.3cis$bca[5])
eur.4 <- subset(europe,europe$Age >= 29 & europe$Age < 31)
boot.eur.4 <- boot(data=eur.4,statistic=maxbrach,R=10000)
boot.eur.4cis <- boot.ci(boot.eur.4,type="bca")
eur.boot4.stats <- c(30,max(boot.eur.4$t),mean(boot.eur.4$t),boot.eur.4cis$bca[4],boot.eur.4cis$bca[5])
eur.5 <- subset(europe,europe$Age >= 28 & europe$Age < 30)
boot.eur.5 <- boot(data=eur.5,statistic=maxbrach,R=10000)
boot.eur.5cis <- boot.ci(boot.eur.5,type="bca")
eur.boot5.stats <- c(29,max(boot.eur.5$t),mean(boot.eur.5$t),boot.eur.5cis$bca[4],boot.eur.5cis$bca[5])
eur.6 <- subset(europe,europe$Age >= 27 & europe$Age < 29)
boot.eur.6 <- boot(data=eur.6,statistic=maxbrach,R=10000)
boot.eur.6cis <- boot.ci(boot.eur.6,type="bca")
eur.boot6.stats <- c(28,max(boot.eur.6$t),mean(boot.eur.6$t),boot.eur.6cis$bca[4],boot.eur.6cis$bca[5])
eur.7 <- subset(europe,europe$Age >= 26 & europe$Age < 28)
boot.eur.7 <- boot(data=eur.7,statistic=maxbrach,R=10000)
boot.eur.7cis <- boot.ci(boot.eur.7,type="bca")
eur.boot7.stats <- c(27,max(boot.eur.7$t),mean(boot.eur.7$t),boot.eur.7cis$bca[4],boot.eur.7cis$bca[5])
eur.8 <- subset(europe,europe$Age >= 25 & europe$Age < 27)
boot.eur.8 <- boot(data=eur.8,statistic=maxbrach,R=10000)
boot.eur.8cis <- boot.ci(boot.eur.8,type="bca")
eur.boot8.stats <- c(26,max(boot.eur.8$t),mean(boot.eur.8$t),boot.eur.8cis$bca[4],boot.eur.8cis$bca[5])
eur.9 <- subset(europe,europe$Age >= 24 & europe$Age < 26)
boot.eur.9 <- boot(data=eur.9,statistic=maxbrach,R=10000)
boot.eur.9cis <- boot.ci(boot.eur.9,type="bca")
eur.boot9.stats <- c(25,max(boot.eur.9$t),mean(boot.eur.9$t),4,4)
eur.10 <- subset(europe,europe$Age >= 23 & europe$Age < 25)
boot.eur.10 <- boot(data=eur.10,statistic=maxbrach,R=10000)
boot.eur.10cis <- boot.ci(boot.eur.10,type="bca")
eur.boot10.stats <- c(24,max(boot.eur.10$t),mean(boot.eur.10$t),boot.eur.10cis$bca[4],boot.eur.10cis$bca[5])
eur.11 <- subset(europe,europe$Age >= 22 & europe$Age < 24)
boot.eur.11 <- boot(data=eur.11,statistic=maxbrach,R=10000)
boot.eur.11cis <- boot.ci(boot.eur.11,type="bca")
eur.boot11.stats <- c(23,max(boot.eur.11$t),mean(boot.eur.11$t),boot.eur.11cis$bca[4],boot.eur.11cis$bca[5])
eur.12 <- subset(europe,europe$Age >= 21 & europe$Age < 23)
boot.eur.12 <- boot(data=eur.12,statistic=maxbrach,R=10000)
boot.eur.12cis <- boot.ci(boot.eur.12,type="bca")
eur.boot12.stats <- c(22,max(boot.eur.12$t),mean(boot.eur.12$t),3,3)
eur.13 <- subset(europe,europe$Age >= 20 & europe$Age < 22)
boot.eur.13 <- boot(data=eur.13,statistic=maxbrach,R=10000)
boot.eur.13cis <- boot.ci(boot.eur.13,type="bca")
eur.boot13.stats <- c(21,max(boot.eur.13$t),mean(boot.eur.13$t),boot.eur.13cis$bca[4],boot.eur.13cis$bca[5])
eur.14 <- subset(europe,europe$Age >= 19 & europe$Age < 21)
boot.eur.14 <- boot(data=eur.14,statistic=maxbrach,R=10000)
boot.eur.14cis <- boot.ci(boot.eur.14,type="bca")
eur.boot14.stats <- c(20,max(boot.eur.14$t),mean(boot.eur.14$t),boot.eur.14cis$bca[4],boot.eur.14cis$bca[5])
eur.15 <- subset(europe,europe$Age >= 18 & europe$Age < 20)
boot.eur.15 <- boot(data=eur.15,statistic=maxbrach,R=10000)
boot.eur.15cis <- boot.ci(boot.eur.15,type="bca")
eur.boot15.stats <- c(19,max(boot.eur.15$t),mean(boot.eur.15$t),boot.eur.15cis$bca[4],boot.eur.15cis$bca[5])
eur.16 <- subset(europe,europe$Age >= 17 & europe$Age < 19)
boot.eur.16 <- boot(data=eur.16,statistic=maxbrach,R=10000)
boot.eur.16cis <- boot.ci(boot.eur.16,type="bca")
eur.boot16.stats <- c(18,max(boot.eur.16$t),mean(boot.eur.16$t),boot.eur.16cis$bca[4],boot.eur.16cis$bca[5])
eur.17 <- subset(europe,europe$Age >= 16 & europe$Age < 18)
boot.eur.17 <- boot(data=eur.17,statistic=maxbrach,R=10000)
boot.eur.17cis <- boot.ci(boot.eur.17,type="bca")
eur.boot17.stats <- c(17,max(boot.eur.17$t),mean(boot.eur.17$t),boot.eur.17cis$bca[4],boot.eur.17cis$bca[5])
eur.18 <- subset(europe,europe$Age >= 15 & europe$Age < 17)
boot.eur.18 <- boot(data=eur.18,statistic=maxbrach,R=10000)
boot.eur.18cis <- boot.ci(boot.eur.18,type="bca")
eur.boot18.stats <- c(16,max(boot.eur.18$t),mean(boot.eur.18$t),boot.eur.18cis$bca[4],boot.eur.18cis$bca[5])
eur.19 <- subset(europe,europe$Age >= 14 & europe$Age < 16)
boot.eur.19 <- boot(data=eur.19,statistic=maxbrach,R=10000)
boot.eur.19cis <- boot.ci(boot.eur.19,type="bca")
eur.boot19.stats <- c(15,max(boot.eur.19$t),mean(boot.eur.19$t),boot.eur.19cis$bca[4],boot.eur.19cis$bca[5])
eur.20 <- subset(europe,europe$Age >= 13 & europe$Age < 15)
boot.eur.20 <- boot(data=eur.20,statistic=maxbrach,R=10000)
eur.boot.eur.20cis <- boot.ci(boot.eur.20,type="bca")
eur.boot20.stats <- c(14,max(boot.eur.20$t),mean(boot.eur.20$t),boot.eur.20cis$bca[4],boot.eur.20cis$bca[5])
eur.21 <- subset(europe,europe$Age >= 12 & europe$Age < 14)
boot.eur.21 <- boot(data=eur.21,statistic=maxbrach,R=10000)
boot.eur.21cis <- boot.ci(boot.eur.21,type="bca")
eur.boot21.stats <- c(13,max(boot.eur.21$t),mean(boot.eur.21$t),boot.eur.21cis$bca[4],boot.eur.21cis$bca[5])
eur.22 <- subset(europe,europe$Age >= 11 & europe$Age < 13)
boot.eur.22 <- boot(data=eur.22,statistic=maxbrach,R=10000)
boot.eur.22cis <- boot.ci(boot.eur.22,type="bca")
eur.boot22.stats <- c(12,max(boot.eur.22$t),mean(boot.eur.22$t),boot.eur.22cis$bca[4],boot.eur.22cis$bca[5])
eur.23 <- subset(europe,europe$Age >= 10 & europe$Age < 12)
boot.eur.23 <- boot(data=eur.23,statistic=maxbrach,R=10000)
boot.eur.23cis <- boot.ci(boot.eur.23,type="bca")
eur.boot23.stats <- c(11,max(boot.eur.23$t),mean(boot.eur.23$t),boot.eur.23cis$bca[4],boot.eur.23cis$bca[5])
eur.24 <- subset(europe,europe$Age >= 9 & europe$Age < 11)
boot.eur.24 <- boot(data=eur.24,statistic=maxbrach,R=10000)
boot.eur.24cis <- boot.ci(boot.eur.24,type="bca")
eur.boot24.stats <- c(10,max(boot.eur.24$t),mean(boot.eur.24$t),boot.eur.24cis$bca[4],9)
eur.25 <- subset(europe,europe$Age >= 8 & europe$Age < 10)
boot.eur.25 <- boot(data=eur.25,statistic=maxbrach,R=10000)
boot.eur.25cis <- boot.ci(boot.eur.25,type="bca")
eur.boot25.stats <- c(9,max(boot.eur.25$t),mean(boot.eur.25$t),boot.eur.25cis$bca[4],8)
eur.26 <- subset(europe,europe$Age >= 7 & europe$Age < 9)
boot.eur.26 <- boot(data=eur.26,statistic=maxbrach,R=10000)
boot.eur.26cis <- boot.ci(boot.eur.26,type="bca")
eur.boot26.stats <- c(8,max(boot.eur.26$t),mean(boot.eur.26$t),boot.eur.26cis$bca[4],boot.eur.26cis$bca[5])
eur.27 <- subset(europe,europe$Age >= 6 & europe$Age < 8)
boot.eur.27 <- boot(data=eur.27,statistic=maxbrach,R=10000)
boot.eur.27cis <- boot.ci(boot.eur.27,type="bca")
eur.boot27.stats <- c(7,max(boot.eur.27$t),mean(boot.eur.27$t),boot.eur.27cis$bca[4],boot.eur.27cis$bca[5])
eur.28 <- subset(europe,europe$Age >= 5 & europe$Age < 7)
boot.eur.28 <- boot(data=eur.28,statistic=maxbrach,R=10000)
boot.eur.28cis <- boot.ci(boot.eur.28,type="bca")
eur.boot28.stats <- c(6,max(boot.eur.28$t),mean(boot.eur.28$t),boot.eur.28cis$bca[4],boot.eur.28cis$bca[5])
eur.29 <- subset(europe,europe$Age >= 4 & europe$Age < 6)
boot.eur.29 <- boot(data=eur.29,statistic=maxbrach,R=10000)
boot.eur.29cis <- boot.ci(boot.eur.29,type="bca")
eur.boot29.stats <- c(5,max(boot.eur.29$t),mean(boot.eur.29$t),boot.eur.29cis$bca[4],boot.eur.29cis$bca[5])
eur.30 <- subset(europe,europe$Age >= 3 & europe$Age < 5)
boot.eur.30 <- boot(data=eur.30,statistic=maxbrach,R=10000)
boot.eur.30cis <- boot.ci(boot.eur.30,type="bca")
eur.boot30.stats <- c(4,max(boot.eur.30$t),mean(boot.eur.30$t),boot.eur.30cis$bca[4],boot.eur.30cis$bca[5])
eur.31 <- subset(europe,europe$Age >= 2 & europe$Age < 4)
boot.eur.31 <- boot(data=eur.31,statistic=maxbrach,R=10000)
boot.eur.31cis <- boot.ci(boot.eur.31,type="bca")
eur.boot31.stats <- c(3,max(boot.eur.31$t),mean(boot.eur.31$t),boot.eur.31cis$bca[4],boot.eur.31cis$bca[5])
eur.32 <- subset(europe,europe$Age >= 1 & europe$Age < 3)
boot.eur.32 <- boot(data=eur.32,statistic=maxbrach,R=10000)
boot.eur.32cis <- boot.ci(boot.eur.32,type="bca")
eur.boot32.stats <- c(2,max(boot.eur.32$t),mean(boot.eur.32$t),boot.eur.32cis$bca[4],6)
eur.33 <- subset(europe,europe$Age >= 0 & europe$Age < 2)
boot.eur.33 <- boot(data=eur.33,statistic=maxbrach,R=10000)
boot.eur.33cis <- boot.ci(boot.eur.33,type="bca")
eur.boot33.stats <- c(1,max(boot.eur.33$t),mean(boot.eur.33$t),boot.eur.33cis$bca[4],boot.eur.33cis$bca[5])

europe.bootstraps <- rbind(eur.boot1.stats,eur.boot2.stats,eur.boot3.stats,eur.boot4.stats,eur.boot5.stats,eur.boot6.stats,eur.boot7.stats,
                           eur.boot8.stats,eur.boot9.stats,eur.boot10.stats,eur.boot11.stats,eur.boot12.stats,eur.boot13.stats,eur.boot14.stats,
                           eur.boot15.stats,eur.boot16.stats,eur.boot17.stats,eur.boot18.stats,eur.boot19.stats,eur.boot20.stats,eur.boot21.stats,
                           eur.boot22.stats,eur.boot23.stats,eur.boot24.stats,eur.boot25.stats,eur.boot26.stats,eur.boot27.stats,eur.boot28.stats,
                           eur.boot29.stats,eur.boot30.stats,eur.boot31.stats,eur.boot32.stats,eur.boot33.stats)
colnames(europe.bootstraps) <- c("Age","Maximum","Mean","CImin","CImax")
europe.bootstraps <- as.data.frame(europe.bootstraps)

europe.boots.plot <- ggplot() + scale_x_reverse("Age (Ma)",limits=c(0,40)) + scale_y_continuous(name="Number of brachydonts",limits=c(0,20)) + 
  geom_errorbar(data = europe.bootstraps,aes(x=Age,ymin=CImin,ymax=CImax),colour="black") +
  geom_point(data=europe.bootstraps,aes(x=Age,y=Maximum),colour="black",size=2) +
  geom_point(data=europe.bootstraps,aes(x=Age,y=Mean),colour="#f8be00",size=2) +
  theme_bw() + coord_geo(pos = list("bottom"), dat = list("epochs"),abbrv = FALSE, expand=TRUE) + theme(text=element_text(size=20))
europe.boots.plot

#Balkanotolia
balk.16 <- subset(balkanotolia,balkanotolia$Age >= 17 & balkanotolia$Age < 19)
boot.balk.16 <- boot(data=balk.16,statistic=maxbrach,R=10000)
boot.balk.16cis <- boot.ci(boot.balk.16,type="bca")
balk.boot16.stats <- c(18,max(boot.balk.16$t),mean(boot.balk.16$t),9,9)
balk.17 <- subset(balkanotolia,balkanotolia$Age >= 16 & balkanotolia$Age < 18)
boot.balk.17 <- boot(data=balk.17,statistic=maxbrach,R=10000)
boot.balk.17cis <- boot.ci(boot.balk.17,type="bca")
balk.boot17.stats <- c(17,max(boot.balk.17$t),mean(boot.balk.17$t),boot.balk.17cis$bca[4],boot.balk.17cis$bca[5])
balk.18 <- subset(balkanotolia,balkanotolia$Age >= 15 & balkanotolia$Age < 17)
boot.balk.18 <- boot(data=balk.18,statistic=maxbrach,R=10000)
boot.balk.18cis <- boot.ci(boot.balk.18,type="bca")
balk.boot18.stats <- c(16,max(boot.balk.18$t),mean(boot.balk.18$t),boot.balk.18cis$bca[4],boot.balk.18cis$bca[5])
balk.boot19.stats <- c(15,NA,NA,NA,NA)
balk.20 <- subset(balkanotolia,balkanotolia$Age >= 13 & balkanotolia$Age < 15)
boot.balk.20 <- boot(data=balk.20,statistic=maxbrach,R=10000)
boot.balk.20cis <- boot.ci(boot.balk.20,type="bca")
balk.boot20.stats <- c(14,max(boot.balk.20$t),mean(boot.balk.20$t),9,9)
balk.21 <- subset(balkanotolia,balkanotolia$Age >= 12 & balkanotolia$Age < 14)
boot.balk.21 <- boot(data=balk.21,statistic=maxbrach,R=10000)
boot.balk.21cis <- boot.ci(boot.balk.21,type="bca")
balk.boot21.stats <- c(13,max(boot.balk.21$t),mean(boot.balk.21$t),boot.balk.21cis$bca[4],boot.balk.21cis$bca[5])
balk.22 <- subset(balkanotolia,balkanotolia$Age >= 11 & balkanotolia$Age < 13)
boot.balk.22 <- boot(data=balk.22,statistic=maxbrach,R=10000)
boot.balk.22cis <- boot.ci(boot.balk.22,type="bca")
balk.boot22.stats <- c(12,max(boot.balk.22$t),mean(boot.balk.22$t),boot.balk.22cis$bca[4],boot.balk.22cis$bca[5])
balk.23 <- subset(balkanotolia,balkanotolia$Age >= 10 & balkanotolia$Age < 12)
boot.balk.23 <- boot(data=balk.23,statistic=maxbrach,R=10000)
boot.balk.23cis <- boot.ci(boot.balk.23,type="bca")
balk.boot23.stats <- c(11,max(boot.balk.23$t),mean(boot.balk.23$t),boot.balk.23cis$bca[4],boot.balk.23cis$bca[5])
balk.24 <- subset(balkanotolia,balkanotolia$Age >= 9 & balkanotolia$Age < 11)
boot.balk.24 <- boot(data=balk.24,statistic=maxbrach,R=10000)
boot.balk.24cis <- boot.ci(boot.balk.24,type="bca")
balk.boot24.stats <- c(10,max(boot.balk.24$t),mean(boot.balk.24$t),boot.balk.24cis$bca[4],boot.balk.24cis$bca[5])
balk.25 <- subset(balkanotolia,balkanotolia$Age >= 8 & balkanotolia$Age < 10)
boot.balk.25 <- boot(data=balk.25,statistic=maxbrach,R=10000)
boot.balk.25cis <- boot.ci(boot.balk.25,type="bca")
balk.boot25.stats <- c(9,max(boot.balk.25$t),mean(boot.balk.25$t),boot.balk.25cis$bca[4],boot.balk.25cis$bca[5])
balk.26 <- subset(balkanotolia,balkanotolia$Age >= 7 & balkanotolia$Age < 9)
boot.balk.26 <- boot(data=balk.26,statistic=maxbrach,R=10000)
boot.balk.26cis <- boot.ci(boot.balk.26,type="bca")
balk.boot26.stats <- c(8,max(boot.balk.26$t),mean(boot.balk.26$t),boot.balk.26cis$bca[4],boot.balk.26cis$bca[5])
balk.27 <- subset(balkanotolia,balkanotolia$Age >= 6 & balkanotolia$Age < 8)
boot.balk.27 <- boot(data=balk.27,statistic=maxbrach,R=10000)
boot.balk.27cis <- boot.ci(boot.balk.27,type="bca")
balk.boot27.stats <- c(7,max(boot.balk.27$t),mean(boot.balk.27$t),boot.balk.27cis$bca[4],boot.balk.27cis$bca[5])
balk.28 <- subset(balkanotolia,balkanotolia$Age >= 5 & balkanotolia$Age < 7)
boot.balk.28 <- boot(data=balk.28,statistic=maxbrach,R=10000)
boot.balk.28cis <- boot.ci(boot.balk.28,type="bca")
balk.boot28.stats <- c(6,max(boot.balk.28$t),mean(boot.balk.28$t),boot.balk.28cis$bca[4],boot.balk.28cis$bca[5])
balk.29 <- subset(balkanotolia,balkanotolia$Age >= 4 & balkanotolia$Age < 6)
boot.balk.29 <- boot(data=balk.29,statistic=maxbrach,R=10000)
boot.balk.29cis <- boot.ci(boot.balk.29,type="bca")
balk.boot29.stats <- c(5,max(boot.balk.29$t),mean(boot.balk.29$t),boot.balk.29cis$bca[4],boot.balk.29cis$bca[5])
balk.30 <- subset(balkanotolia,balkanotolia$Age >= 3 & balkanotolia$Age < 5)
boot.balk.30 <- boot(data=balk.30,statistic=maxbrach,R=10000)
boot.balk.30cis <- boot.ci(boot.balk.30,type="bca")
balk.boot30.stats <- c(4,max(boot.balk.30$t),mean(boot.balk.30$t),boot.balk.30cis$bca[4],boot.balk.30cis$bca[5])
balk.31 <- subset(balkanotolia,balkanotolia$Age >= 2 & balkanotolia$Age < 4)
boot.balk.31 <- boot(data=balk.31,statistic=maxbrach,R=10000)
boot.balk.31cis <- boot.ci(boot.balk.31,type="bca")
balk.boot31.stats <- c(3,max(boot.balk.31$t),mean(boot.balk.31$t),boot.balk.31cis$bca[4],boot.balk.31cis$bca[5])
balk.32 <- subset(balkanotolia,balkanotolia$Age >= 1 & balkanotolia$Age < 3)
boot.balk.32 <- boot(data=balk.32,statistic=maxbrach,R=10000)
boot.balk.32cis <- boot.ci(boot.balk.32,type="bca")
balk.boot32.stats <- c(2,max(boot.balk.32$t),mean(boot.balk.32$t),boot.balk.32cis$bca[4],boot.balk.32cis$bca[5])
balk.33 <- subset(balkanotolia,balkanotolia$Age >= 0 & balkanotolia$Age < 2)
boot.balk.33 <- boot(data=balk.33,statistic=maxbrach,R=10000)
boot.balk.33cis <- boot.ci(boot.balk.33,type="bca")
balk.boot33.stats <- c(1,max(boot.balk.33$t),mean(boot.balk.33$t),boot.balk.33cis$bca[4],boot.balk.33cis$bca[5])

balkanotolia.bootstraps <- rbind(balk.boot16.stats,balk.boot17.stats,balk.boot18.stats,balk.boot19.stats,balk.boot20.stats,balk.boot21.stats,
                                 balk.boot22.stats,balk.boot23.stats,balk.boot24.stats,balk.boot25.stats,balk.boot26.stats,balk.boot27.stats,balk.boot28.stats,
                                 balk.boot29.stats,balk.boot30.stats,balk.boot31.stats,balk.boot32.stats,balk.boot33.stats)
colnames(balkanotolia.bootstraps) <- c("Age","Maximum","Mean","CImin","CImax")
balkanotolia.bootstraps <- as.data.frame(balkanotolia.bootstraps)

balkanotolia.boots.plot <- ggplot() + scale_x_reverse("Age (Ma)",limits=c(0,40)) + scale_y_continuous(name="Number of brachydonts",limits=c(0,20)) + 
  geom_errorbar(data = balkanotolia.bootstraps,aes(x=Age,ymin=CImin,ymax=CImax),colour="black") +
  geom_point(data=balkanotolia.bootstraps,aes(x=Age,y=Maximum),colour="black",size=2) +
  geom_point(data=balkanotolia.bootstraps,aes(x=Age,y=Mean),colour="#a00509",size=2) +
  theme_bw() + coord_geo(pos = list("bottom"), dat = list("epochs"),abbrv = FALSE, expand=TRUE) + theme(text=element_text(size=20))
balkanotolia.boots.plot

#Central Asia
centralasia.1 <- subset(centralasia,centralasia$Age >= 32 & centralasia$Age < 34)
boot.centralasia.1 <- boot(data=centralasia.1,statistic=maxbrach,R=10000)
boot.centralasia.1cis <- boot.ci(boot.centralasia.1,type="bca")
centralasia.boot1.stats <- c(33,max(boot.centralasia.1$t),mean(boot.centralasia.1$t),boot.centralasia.1cis$bca[4],boot.centralasia.1cis$bca[5])
centralasia.2 <- subset(centralasia,centralasia$Age >= 31 & centralasia$Age < 33)
boot.centralasia.2 <- boot(data=centralasia.2,statistic=maxbrach,R=10000)
boot.centralasia.2cis <- boot.ci(boot.centralasia.2,type="bca")
centralasia.boot2.stats <- c(32,max(boot.centralasia.2$t),mean(boot.centralasia.2$t),boot.centralasia.2cis$bca[4],boot.centralasia.2cis$bca[5])
centralasia.3 <- subset(centralasia,centralasia$Age >= 30 & centralasia$Age < 32)
boot.centralasia.3 <- boot(data=centralasia.3,statistic=maxbrach,R=10000)
boot.centralasia.3cis <- boot.ci(boot.centralasia.3,type="bca")
centralasia.boot3.stats <- c(31,max(boot.centralasia.3$t),mean(boot.centralasia.3$t),boot.centralasia.3cis$bca[4],7)
centralasia.4 <- subset(centralasia,centralasia$Age >= 29 & centralasia$Age < 31)
boot.centralasia.4 <- boot(data=centralasia.4,statistic=maxbrach,R=10000)
boot.centralasia.4cis <- boot.ci(boot.centralasia.4,type="bca")
centralasia.boot4.stats <- c(30,max(boot.centralasia.4$t),mean(boot.centralasia.4$t),boot.centralasia.4cis$bca[4],boot.centralasia.4cis$bca[5])
centralasia.5 <- subset(centralasia,centralasia$Age >= 28 & centralasia$Age < 30)
boot.centralasia.5 <- boot(data=centralasia.5,statistic=maxbrach,R=10000)
boot.centralasia.5cis <- boot.ci(boot.centralasia.5,type="bca")
centralasia.boot5.stats <- c(29,max(boot.centralasia.5$t),mean(boot.centralasia.5$t),boot.centralasia.5cis$bca[4],boot.centralasia.5cis$bca[5])
centralasia.6 <- subset(centralasia,centralasia$Age >= 27 & centralasia$Age < 29)
boot.centralasia.6 <- boot(data=centralasia.6,statistic=maxbrach,R=10000)
boot.centralasia.6cis <- boot.ci(boot.centralasia.6,type="bca")
centralasia.boot6.stats <- c(28,max(boot.centralasia.6$t),mean(boot.centralasia.6$t),5,5)
centralasia.7 <- subset(centralasia,centralasia$Age >= 26 & centralasia$Age < 28)
boot.centralasia.7 <- boot(data=centralasia.7,statistic=maxbrach,R=10000)
boot.centralasia.7cis <- boot.ci(boot.centralasia.7,type="bca")
centralasia.boot7.stats <- c(27,max(boot.centralasia.7$t),mean(boot.centralasia.7$t),5,5)
centralasia.8 <- subset(centralasia,centralasia$Age >= 25 & centralasia$Age < 27)
boot.centralasia.8 <- boot(data=centralasia.8,statistic=maxbrach,R=10000)
boot.centralasia.8cis <- boot.ci(boot.centralasia.8,type="bca")
centralasia.boot8.stats <- c(26,max(boot.centralasia.8$t),mean(boot.centralasia.8$t),boot.centralasia.8cis$bca[4],boot.centralasia.8cis$bca[5])
centralasia.9 <- subset(centralasia,centralasia$Age >= 24 & centralasia$Age < 26)
boot.centralasia.9 <- boot(data=centralasia.9,statistic=maxbrach,R=10000)
boot.centralasia.9cis <- boot.ci(boot.centralasia.9,type="bca")
centralasia.boot9.stats <- c(25,max(boot.centralasia.9$t),mean(boot.centralasia.9$t),boot.centralasia.9cis$bca[4],boot.centralasia.9cis$bca[5])
centralasia.10 <- subset(centralasia,centralasia$Age >= 23 & centralasia$Age < 25)
boot.centralasia.10 <- boot(data=centralasia.10,statistic=maxbrach,R=10000)
boot.centralasia.10cis <- boot.ci(boot.centralasia.10,type="bca")
centralasia.boot10.stats <- c(24,max(boot.centralasia.10$t),mean(boot.centralasia.10$t),boot.centralasia.10cis$bca[4],boot.centralasia.10cis$bca[5])
centralasia.11 <- subset(centralasia,centralasia$Age >= 22 & centralasia$Age < 24)
boot.centralasia.11 <- boot(data=centralasia.11,statistic=maxbrach,R=10000)
boot.centralasia.11cis <- boot.ci(boot.centralasia.11,type="bca")
centralasia.boot11.stats <- c(23,max(boot.centralasia.11$t),mean(boot.centralasia.11$t),boot.centralasia.11cis$bca[4],boot.centralasia.11cis$bca[5])
centralasia.boot12.stats <- c(22,NA,NA,NA,NA)
centralasia.13 <- subset(centralasia,centralasia$Age >= 20 & centralasia$Age < 22)
boot.centralasia.13 <- boot(data=centralasia.13,statistic=maxbrach,R=10000)
boot.centralasia.13cis <- boot.ci(boot.centralasia.13,type="bca")
centralasia.boot13.stats <- c(21,max(boot.centralasia.13$t),mean(boot.centralasia.13$t),3,3)
centralasia.14 <- subset(centralasia,centralasia$Age >= 19 & centralasia$Age < 21)
boot.centralasia.14 <- boot(data=centralasia.14,statistic=maxbrach,R=10000)
boot.centralasia.14cis <- boot.ci(boot.centralasia.14,type="bca")
centralasia.boot14.stats <- c(20,max(boot.centralasia.14$t),mean(boot.centralasia.14$t),3,3)
centralasia.15 <- subset(centralasia,centralasia$Age >= 18 & centralasia$Age < 20)
boot.centralasia.15 <- boot(data=centralasia.15,statistic=maxbrach,R=10000)
boot.centralasia.15cis <- boot.ci(boot.centralasia.15,type="bca")
centralasia.boot15.stats <- c(19,max(boot.centralasia.15$t),mean(boot.centralasia.15$t),boot.centralasia.15cis$bca[4],boot.centralasia.15cis$bca[5])
centralasia.16 <- subset(centralasia,centralasia$Age >= 17 & centralasia$Age < 19)
boot.centralasia.16 <- boot(data=centralasia.16,statistic=maxbrach,R=10000)
boot.centralasia.16cis <- boot.ci(boot.centralasia.16,type="bca")
centralasia.boot16.stats <- c(18,max(boot.centralasia.16$t),mean(boot.centralasia.16$t),boot.centralasia.16cis$bca[4],boot.centralasia.16cis$bca[5])
centralasia.17 <- subset(centralasia,centralasia$Age >= 16 & centralasia$Age < 18)
boot.centralasia.17 <- boot(data=centralasia.17,statistic=maxbrach,R=10000)
boot.centralasia.17cis <- boot.ci(boot.centralasia.17,type="bca")
centralasia.boot17.stats <- c(17,max(boot.centralasia.17$t),mean(boot.centralasia.17$t),boot.centralasia.17cis$bca[4],boot.centralasia.17cis$bca[5])
centralasia.18 <- subset(centralasia,centralasia$Age >= 15 & centralasia$Age < 17)
boot.centralasia.18 <- boot(data=centralasia.18,statistic=maxbrach,R=10000)
boot.centralasia.18cis <- boot.ci(boot.centralasia.18,type="bca")
centralasia.boot18.stats <- c(16,max(boot.centralasia.18$t),mean(boot.centralasia.18$t),boot.centralasia.18cis$bca[4],boot.centralasia.18cis$bca[5])
centralasia.19 <- subset(centralasia,centralasia$Age >= 14 & centralasia$Age < 16)
boot.centralasia.19 <- boot(data=centralasia.19,statistic=maxbrach,R=10000)
boot.centralasia.19cis <- boot.ci(boot.centralasia.19,type="bca")
centralasia.boot19.stats <- c(15,max(boot.centralasia.19$t),mean(boot.centralasia.19$t),boot.centralasia.19cis$bca[4],boot.centralasia.19cis$bca[5])
centralasia.20 <- subset(centralasia,centralasia$Age >= 13 & centralasia$Age < 15)
boot.centralasia.20 <- boot(data=centralasia.20,statistic=maxbrach,R=10000)
boot.centralasia.20cis <- boot.ci(boot.centralasia.20,type="bca")
centralasia.boot20.stats <- c(14,max(boot.centralasia.20$t),mean(boot.centralasia.20$t),4,4)
centralasia.21 <- subset(centralasia,centralasia$Age >= 12 & centralasia$Age < 14)
boot.centralasia.21 <- boot(data=centralasia.21,statistic=maxbrach,R=10000)
boot.centralasia.21cis <- boot.ci(boot.centralasia.21,type="bca")
centralasia.boot21.stats <- c(13,max(boot.centralasia.21$t),mean(boot.centralasia.21$t),boot.centralasia.21cis$bca[4],boot.centralasia.21cis$bca[5])
centralasia.22 <- subset(centralasia,centralasia$Age >= 11 & centralasia$Age < 13)
boot.centralasia.22 <- boot(data=centralasia.22,statistic=maxbrach,R=10000)
boot.centralasia.22cis <- boot.ci(boot.centralasia.22,type="bca")
centralasia.boot22.stats <- c(12,max(boot.centralasia.22$t),mean(boot.centralasia.22$t),boot.centralasia.22cis$bca[4],boot.centralasia.22cis$bca[5])
centralasia.23 <- subset(centralasia,centralasia$Age >= 10 & centralasia$Age < 12)
boot.centralasia.23 <- boot(data=centralasia.23,statistic=maxbrach,R=10000)
boot.centralasia.23cis <- boot.ci(boot.centralasia.23,type="bca")
centralasia.boot23.stats <- c(11,max(boot.centralasia.23$t),mean(boot.centralasia.23$t),boot.centralasia.23cis$bca[4],boot.centralasia.23cis$bca[5])
centralasia.24 <- subset(centralasia,centralasia$Age >= 9 & centralasia$Age < 11)
boot.centralasia.24 <- boot(data=centralasia.24,statistic=maxbrach,R=10000)
boot.centralasia.24cis <- boot.ci(boot.centralasia.24,type="bca")
centralasia.boot24.stats <- c(10,max(boot.centralasia.24$t),mean(boot.centralasia.24$t),boot.centralasia.24cis$bca[4],boot.centralasia.24cis$bca[5])
centralasia.25 <- subset(centralasia,centralasia$Age >= 8 & centralasia$Age < 10)
boot.centralasia.25 <- boot(data=centralasia.25,statistic=maxbrach,R=10000)
boot.centralasia.25cis <- boot.ci(boot.centralasia.25,type="bca")
centralasia.boot25.stats <- c(9,max(boot.centralasia.25$t),mean(boot.centralasia.25$t),boot.centralasia.25cis$bca[4],boot.centralasia.25cis$bca[5])
centralasia.26 <- subset(centralasia,centralasia$Age >= 7 & centralasia$Age < 9)
boot.centralasia.26 <- boot(data=centralasia.26,statistic=maxbrach,R=10000)
boot.centralasia.26cis <- boot.ci(boot.centralasia.26,type="bca")
centralasia.boot26.stats <- c(8,max(boot.centralasia.26$t),mean(boot.centralasia.26$t),boot.centralasia.26cis$bca[4],boot.centralasia.26cis$bca[5])
centralasia.27 <- subset(centralasia,centralasia$Age >= 6 & centralasia$Age < 8)
boot.centralasia.27 <- boot(data=centralasia.27,statistic=maxbrach,R=10000)
boot.centralasia.27cis <- boot.ci(boot.centralasia.27,type="bca")
centralasia.boot27.stats <- c(7,max(boot.centralasia.27$t),mean(boot.centralasia.27$t),boot.centralasia.27cis$bca[4],boot.centralasia.27cis$bca[5])
centralasia.28 <- subset(centralasia,centralasia$Age >= 5 & centralasia$Age < 7)
boot.centralasia.28 <- boot(data=centralasia.28,statistic=maxbrach,R=10000)
boot.centralasia.28cis <- boot.ci(boot.centralasia.28,type="bca")
centralasia.boot28.stats <- c(6,max(boot.centralasia.28$t),mean(boot.centralasia.28$t),boot.centralasia.28cis$bca[4],boot.centralasia.28cis$bca[5])
centralasia.29 <- subset(centralasia,centralasia$Age >= 4 & centralasia$Age < 6)
boot.centralasia.29 <- boot(data=centralasia.29,statistic=maxbrach,R=10000)
boot.centralasia.29cis <- boot.ci(boot.centralasia.29,type="bca")
centralasia.boot29.stats <- c(5,max(boot.centralasia.29$t),mean(boot.centralasia.29$t),boot.centralasia.29cis$bca[4],3)
centralasia.30 <- subset(centralasia,centralasia$Age >= 3 & centralasia$Age < 5)
boot.centralasia.30 <- boot(data=centralasia.30,statistic=maxbrach,R=10000)
boot.centralasia.30cis <- boot.ci(boot.centralasia.30,type="bca")
centralasia.boot30.stats <- c(4,max(boot.centralasia.30$t),mean(boot.centralasia.30$t),boot.centralasia.30cis$bca[4],boot.centralasia.30cis$bca[5])
centralasia.31 <- subset(centralasia,centralasia$Age >= 2 & centralasia$Age < 4)
boot.centralasia.31 <- boot(data=centralasia.31,statistic=maxbrach,R=10000)
boot.centralasia.31cis <- boot.ci(boot.centralasia.31,type="bca")
centralasia.boot31.stats <- c(3,max(boot.centralasia.31$t),mean(boot.centralasia.31$t),boot.centralasia.31cis$bca[4],boot.centralasia.31cis$bca[5])
centralasia.32 <- subset(centralasia,centralasia$Age >= 1 & centralasia$Age < 3)
boot.centralasia.32 <- boot(data=centralasia.32,statistic=maxbrach,R=10000)
boot.centralasia.32cis <- boot.ci(boot.centralasia.32,type="bca")
centralasia.boot32.stats <- c(2,max(boot.centralasia.32$t),mean(boot.centralasia.32$t),boot.centralasia.32cis$bca[4],boot.centralasia.32cis$bca[5])
centralasia.33 <- subset(centralasia,centralasia$Age >= 0 & centralasia$Age < 2)
boot.centralasia.33 <- boot(data=centralasia.33,statistic=maxbrach,R=10000)
boot.centralasia.33cis <- boot.ci(boot.centralasia.33,type="bca")
centralasia.boot33.stats <- c(1,max(boot.centralasia.33$t),mean(boot.centralasia.33$t),boot.centralasia.33cis$bca[4],boot.centralasia.33cis$bca[5])

centralasia.bootstraps <- rbind(centralasia.boot1.stats,centralasia.boot2.stats,centralasia.boot3.stats,centralasia.boot4.stats,centralasia.boot5.stats,centralasia.boot6.stats,centralasia.boot7.stats,
                                centralasia.boot8.stats,centralasia.boot9.stats,centralasia.boot10.stats,centralasia.boot11.stats,centralasia.boot12.stats,centralasia.boot13.stats,centralasia.boot14.stats,
                                centralasia.boot15.stats,centralasia.boot16.stats,centralasia.boot17.stats,centralasia.boot18.stats,centralasia.boot19.stats,centralasia.boot20.stats,centralasia.boot21.stats,
                                centralasia.boot22.stats,centralasia.boot23.stats,centralasia.boot24.stats,centralasia.boot25.stats,centralasia.boot26.stats,centralasia.boot27.stats,centralasia.boot28.stats,
                                centralasia.boot29.stats,centralasia.boot30.stats,centralasia.boot31.stats,centralasia.boot32.stats,centralasia.boot33.stats)
colnames(centralasia.bootstraps) <- c("Age","Maximum","Mean","CImin","CImax")
centralasia.bootstraps <- as.data.frame(centralasia.bootstraps)

centralasia.boots.plot <- ggplot() + scale_x_reverse("Age (Ma)",limits=c(0,40)) + scale_y_continuous(name="Number of brachydonts",limits=c(0,20)) + 
  geom_errorbar(data = centralasia.bootstraps,aes(x=Age,ymin=CImin,ymax=CImax),colour="black") +
  geom_point(data=centralasia.bootstraps,aes(x=Age,y=Maximum),colour="black",size=2) +
  geom_point(data=centralasia.bootstraps,aes(x=Age,y=Mean),colour="#10a6c0",size=2) +
  theme_bw() + coord_geo(pos = list("bottom"), dat = list("epochs"),abbrv = FALSE, expand=TRUE) + theme(text=element_text(size=20))
centralasia.boots.plot

#Indian subcontinent
india.3 <- subset(india,india$Age >= 30 & india$Age < 32)
boot.india.3 <- boot(data=india.3,statistic=maxbrach,R=10000)
boot.india.3cis <- boot.ci(boot.india.3,type="bca")
india.boot3.stats <- c(31,max(boot.india.3$t),mean(boot.india.3$t),2,2)
india.4 <- subset(india,india$Age >= 29 & india$Age < 31)
boot.india.4 <- boot(data=india.4,statistic=maxbrach,R=10000)
boot.india.4cis <- boot.ci(boot.india.4,type="bca")
india.boot4.stats <- c(30,max(boot.india.4$t),mean(boot.india.4$t),2,2)
india.boot5.stats <- c(29,NA,NA,NA,NA)
india.boot6.stats <- c(28,NA,NA,NA,NA)
india.7 <- subset(india,india$Age >= 26 & india$Age < 28)
boot.india.7 <- boot(data=india.7,statistic=maxbrach,R=10000)
boot.india.7cis <- boot.ci(boot.india.7,type="bca")
india.boot7.stats <- c(27,max(boot.india.7$t),mean(boot.india.7$t),5,5)
india.8 <- subset(india,india$Age >= 25 & india$Age < 27)
boot.india.8 <- boot(data=india.8,statistic=maxbrach,R=10000)
boot.india.8cis <- boot.ci(boot.india.8,type="bca")
india.boot8.stats <- c(26,max(boot.india.8$t),mean(boot.india.8$t),boot.india.8cis$bca[4],boot.india.8cis$bca[5])
india.9 <- subset(india,india$Age >= 24 & india$Age < 26)
boot.india.9 <- boot(data=india.9,statistic=maxbrach,R=10000)
boot.india.9cis <- boot.ci(boot.india.9,type="bca")
india.boot9.stats <- c(25,max(boot.india.9$t),mean(boot.india.9$t),9,9)
india.10 <- subset(india,india$Age >= 23 & india$Age < 25)
boot.india.10 <- boot(data=india.10,statistic=maxbrach,R=10000)
boot.india.10cis <- boot.ci(boot.india.10,type="bca")
india.boot10.stats <- c(24,max(boot.india.10$t),mean(boot.india.10$t),6,6)
india.11 <- subset(india,india$Age >= 22 & india$Age < 24)
boot.india.11 <- boot(data=india.11,statistic=maxbrach,R=10000)
boot.india.11cis <- boot.ci(boot.india.11,type="bca")
india.boot11.stats <- c(23,max(boot.india.11$t),mean(boot.india.11$t),6,6)
india.12 <- subset(india,india$Age >= 21 & india$Age < 23)
boot.india.12 <- boot(data=india.12,statistic=maxbrach,R=10000)
boot.india.12cis <- boot.ci(boot.india.12,type="bca")
india.boot12.stats <- c(22,max(boot.india.12$t),mean(boot.india.12$t),6,6)
india.13 <- subset(india,india$Age >= 20 & india$Age < 22)
boot.india.13 <- boot(data=india.13,statistic=maxbrach,R=10000)
boot.india.13cis <- boot.ci(boot.india.13,type="bca")
india.boot13.stats <- c(21,max(boot.india.13$t),mean(boot.india.13$t),6,6)
india.14 <- subset(india,india$Age >= 19 & india$Age < 21)
boot.india.14 <- boot(data=india.14,statistic=maxbrach,R=10000)
boot.india.14cis <- boot.ci(boot.india.14,type="bca")
india.boot14.stats <- c(20,max(boot.india.14$t),mean(boot.india.14$t),9,9)
india.15 <- subset(india,india$Age >= 18 & india$Age < 20)
boot.india.15 <- boot(data=india.15,statistic=maxbrach,R=10000)
boot.india.15cis <- boot.ci(boot.india.15,type="bca")
india.boot15.stats <- c(19,max(boot.india.15$t),mean(boot.india.15$t),boot.india.15cis$bca[4],boot.india.15cis$bca[5])
india.16 <- subset(india,india$Age >= 17 & india$Age < 19)
boot.india.16 <- boot(data=india.16,statistic=maxbrach,R=10000)
boot.india.16cis <- boot.ci(boot.india.16,type="bca")
india.boot16.stats <- c(18,max(boot.india.16$t),mean(boot.india.16$t),boot.india.16cis$bca[4],boot.india.16cis$bca[5])
india.17 <- subset(india,india$Age >= 16 & india$Age < 18)
boot.india.17 <- boot(data=india.17,statistic=maxbrach,R=10000)
boot.india.17cis <- boot.ci(boot.india.17,type="bca")
india.boot17.stats <- c(17,max(boot.india.17$t),mean(boot.india.17$t),13,13)
india.18 <- subset(india,india$Age >= 15 & india$Age < 17)
boot.india.18 <- boot(data=india.18,statistic=maxbrach,R=10000)
boot.india.18cis <- boot.ci(boot.india.18,type="bca")
india.boot18.stats <- c(16,max(boot.india.18$t),mean(boot.india.18$t),boot.india.18cis$bca[4],boot.india.18cis$bca[5])
india.19 <- subset(india,india$Age >= 14 & india$Age < 16)
boot.india.19 <- boot(data=india.19,statistic=maxbrach,R=10000)
boot.india.19cis <- boot.ci(boot.india.19,type="bca")
india.boot19.stats <- c(15,max(boot.india.19$t),mean(boot.india.19$t),boot.india.19cis$bca[4],boot.india.19cis$bca[5])
india.boot20.stats <- c(14,NA,NA,NA,NA)
india.21 <- subset(india,india$Age >= 12 & india$Age < 14)
boot.india.21 <- boot(data=india.21,statistic=maxbrach,R=10000)
boot.india.21cis <- boot.ci(boot.india.21,type="bca")
india.boot21.stats <- c(13,max(boot.india.21$t),mean(boot.india.21$t),boot.india.21cis$bca[4],boot.india.21cis$bca[5])
india.22 <- subset(india,india$Age >= 11 & india$Age < 13)
boot.india.22 <- boot(data=india.22,statistic=maxbrach,R=10000)
boot.india.22cis <- boot.ci(boot.india.22,type="bca")
india.boot22.stats <- c(12,max(boot.india.22$t),mean(boot.india.22$t),boot.india.22cis$bca[4],boot.india.22cis$bca[5])
india.23 <- subset(india,india$Age >= 10 & india$Age < 12)
boot.india.23 <- boot(data=india.23,statistic=maxbrach,R=10000)
boot.india.23cis <- boot.ci(boot.india.23,type="bca")
india.boot23.stats <- c(11,max(boot.india.23$t),mean(boot.india.23$t),3,3)
india.24 <- subset(india,india$Age >= 9 & india$Age < 11)
boot.india.24 <- boot(data=india.24,statistic=maxbrach,R=10000)
boot.india.24cis <- boot.ci(boot.india.24,type="bca")
india.boot24.stats <- c(10,max(boot.india.24$t),mean(boot.india.24$t),boot.india.24cis$bca[4],boot.india.24cis$bca[5])
india.25 <- subset(india,india$Age >= 8 & india$Age < 10)
boot.india.25 <- boot(data=india.25,statistic=maxbrach,R=10000)
boot.india.25cis <- boot.ci(boot.india.25,type="bca")
india.boot25.stats <- c(9,max(boot.india.25$t),mean(boot.india.25$t),boot.india.25cis$bca[4],boot.india.25cis$bca[5])
india.26 <- subset(india,india$Age >= 7 & india$Age < 9)
boot.india.26 <- boot(data=india.26,statistic=maxbrach,R=10000)
boot.india.26cis <- boot.ci(boot.india.26,type="bca")
india.boot26.stats <- c(8,max(boot.india.26$t),mean(boot.india.26$t),boot.india.26cis$bca[4],boot.india.26cis$bca[5])
india.boot27.stats <- c(7,NA,NA,NA,NA)
india.28 <- subset(india,india$Age >= 5 & india$Age < 7)
boot.india.28 <- boot(data=india.28,statistic=maxbrach,R=10000)
boot.india.28cis <- boot.ci(boot.india.28,type="bca")
india.boot28.stats <- c(6,max(boot.india.28$t),mean(boot.india.28$t),2,2)
india.29 <- subset(india,india$Age >= 4 & india$Age < 6)
boot.india.29 <- boot(data=india.29,statistic=maxbrach,R=10000)
boot.india.29cis <- boot.ci(boot.india.29,type="bca")
india.boot29.stats <- c(5,max(boot.india.29$t),mean(boot.india.29$t),2,2)
india.30 <- subset(india,india$Age >= 3 & india$Age < 5)
boot.india.30 <- boot(data=india.30,statistic=maxbrach,R=10000)
boot.india.30cis <- boot.ci(boot.india.30,type="bca")
india.boot30.stats <- c(4,max(boot.india.30$t),mean(boot.india.30$t),boot.india.30cis$bca[4],boot.india.30cis$bca[5])
india.31 <- subset(india,india$Age >= 2 & india$Age < 4)
boot.india.31 <- boot(data=india.31,statistic=maxbrach,R=10000)
boot.india.31cis <- boot.ci(boot.india.31,type="bca")
india.boot31.stats <- c(3,max(boot.india.31$t),mean(boot.india.31$t),boot.india.31cis$bca[4],boot.india.31cis$bca[5])
india.32 <- subset(india,india$Age >= 1 & india$Age < 3)
boot.india.32 <- boot(data=india.32,statistic=maxbrach,R=10000)
boot.india.32cis <- boot.ci(boot.india.32,type="bca")
india.boot32.stats <- c(2,max(boot.india.32$t),mean(boot.india.32$t),2,2)
india.33 <- subset(india,india$Age >= 0 & india$Age < 2)
boot.india.33 <- boot(data=india.33,statistic=maxbrach,R=10000)
boot.india.33cis <- boot.ci(boot.india.33,type="bca")
india.boot33.stats <- c(1,max(boot.india.33$t),mean(boot.india.33$t),boot.india.33cis$bca[4],boot.india.33cis$bca[5])

india.bootstraps <- rbind(india.boot3.stats,india.boot4.stats,india.boot5.stats,india.boot6.stats,india.boot7.stats,india.boot8.stats,india.boot9.stats,india.boot10.stats,india.boot11.stats,india.boot12.stats,india.boot13.stats,india.boot14.stats,
                          india.boot15.stats,india.boot16.stats,india.boot17.stats,india.boot18.stats,india.boot19.stats,india.boot20.stats,india.boot21.stats,
                          india.boot22.stats,india.boot23.stats,india.boot24.stats,india.boot25.stats,india.boot26.stats,india.boot27.stats,india.boot28.stats,
                          india.boot29.stats,india.boot30.stats,india.boot31.stats,india.boot32.stats,india.boot33.stats)
colnames(india.bootstraps) <- c("Age","Maximum","Mean","CImin","CImax")
india.bootstraps <- as.data.frame(india.bootstraps)

india.boots.plot <- ggplot() + scale_x_reverse("Age (Ma)",limits=c(0,40)) + scale_y_continuous(name="Number of brachydonts",limits=c(0,20)) + 
  geom_errorbar(data = india.bootstraps,aes(x=Age,ymin=CImin,ymax=CImax),colour="black") +
  geom_point(data=india.bootstraps,aes(x=Age,y=Maximum),colour="black",size=2) +
  geom_point(data=india.bootstraps,aes(x=Age,y=Mean),colour="#21215f",size=2) +
  theme_bw() + coord_geo(pos = list("bottom"), dat = list("epochs"),abbrv = FALSE, expand=TRUE) + theme(text=element_text(size=20))
india.boots.plot

#Eastern Africa
eastafrica.5 <- subset(eastafrica,eastafrica$Age >= 28 & eastafrica$Age < 30)
boot.eastafrica.5 <- boot(data=eastafrica.5,statistic=maxbrach,R=10000)
boot.eastafrica.5cis <- boot.ci(boot.eastafrica.5,type="bca")
eastafrica.boot5.stats <- c(29,max(boot.eastafrica.5$t),mean(boot.eastafrica.5$t),3,3)
eastafrica.6 <- subset(eastafrica,eastafrica$Age >= 27 & eastafrica$Age < 29)
boot.eastafrica.6 <- boot(data=eastafrica.6,statistic=maxbrach,R=10000)
boot.eastafrica.6cis <- boot.ci(boot.eastafrica.6,type="bca")
eastafrica.boot6.stats <- c(28,max(boot.eastafrica.6$t),mean(boot.eastafrica.6$t),3,3)
eastafrica.boot7.stats <- c(27,NA,NA,NA,NA)
eastafrica.boot8.stats <- c(26,NA,NA,NA,NA)
eastafrica.boot9.stats <- c(25,NA,NA,NA,NA)
eastafrica.boot10.stats <- c(24,NA,NA,NA,NA)
eastafrica.boot11.stats <- c(23,NA,NA,NA,NA)
eastafrica.12 <- subset(eastafrica,eastafrica$Age >= 21 & eastafrica$Age < 23)
boot.eastafrica.12 <- boot(data=eastafrica.12,statistic=maxbrach,R=10000)
boot.eastafrica.12cis <- boot.ci(boot.eastafrica.12,type="bca")
eastafrica.boot12.stats <- c(22,max(boot.eastafrica.12$t),mean(boot.eastafrica.12$t),5,5)
eastafrica.13 <- subset(eastafrica,eastafrica$Age >= 20 & eastafrica$Age < 22)
boot.eastafrica.13 <- boot(data=eastafrica.13,statistic=maxbrach,R=10000)
boot.eastafrica.13cis <- boot.ci(boot.eastafrica.13,type="bca")
eastafrica.boot13.stats <- c(21,max(boot.eastafrica.13$t),mean(boot.eastafrica.13$t),boot.eastafrica.13cis$bca[4],boot.eastafrica.13cis$bca[5])
eastafrica.14 <- subset(eastafrica,eastafrica$Age >= 19 & eastafrica$Age < 21)
boot.eastafrica.14 <- boot(data=eastafrica.14,statistic=maxbrach,R=10000)
boot.eastafrica.14cis <- boot.ci(boot.eastafrica.14,type="bca")
eastafrica.boot14.stats <- c(20,max(boot.eastafrica.14$t),mean(boot.eastafrica.14$t),boot.eastafrica.14cis$bca[4],boot.eastafrica.14cis$bca[5])
eastafrica.15 <- subset(eastafrica,eastafrica$Age >= 18 & eastafrica$Age < 20)
boot.eastafrica.15 <- boot(data=eastafrica.15,statistic=maxbrach,R=10000)
boot.eastafrica.15cis <- boot.ci(boot.eastafrica.15,type="bca")
eastafrica.boot15.stats <- c(19,max(boot.eastafrica.15$t),mean(boot.eastafrica.15$t),boot.eastafrica.15cis$bca[4],boot.eastafrica.15cis$bca[5])
eastafrica.16 <- subset(eastafrica,eastafrica$Age >= 17 & eastafrica$Age < 19)
boot.eastafrica.16 <- boot(data=eastafrica.16,statistic=maxbrach,R=10000)
boot.eastafrica.16cis <- boot.ci(boot.eastafrica.16,type="bca")
eastafrica.boot16.stats <- c(18,max(boot.eastafrica.16$t),mean(boot.eastafrica.16$t),boot.eastafrica.16cis$bca[4],boot.eastafrica.16cis$bca[5])
eastafrica.17 <- subset(eastafrica,eastafrica$Age >= 16 & eastafrica$Age < 18)
boot.eastafrica.17 <- boot(data=eastafrica.17,statistic=maxbrach,R=10000)
boot.eastafrica.17cis <- boot.ci(boot.eastafrica.17,type="bca")
eastafrica.boot17.stats <- c(17,max(boot.eastafrica.17$t),mean(boot.eastafrica.17$t),boot.eastafrica.17cis$bca[4],boot.eastafrica.17cis$bca[5])
eastafrica.18 <- subset(eastafrica,eastafrica$Age >= 15 & eastafrica$Age < 17)
boot.eastafrica.18 <- boot(data=eastafrica.18,statistic=maxbrach,R=10000)
boot.eastafrica.18cis <- boot.ci(boot.eastafrica.18,type="bca")
eastafrica.boot18.stats <- c(16,max(boot.eastafrica.18$t),mean(boot.eastafrica.18$t),boot.eastafrica.18cis$bca[4],boot.eastafrica.18cis$bca[5])
eastafrica.boot19.stats <- c(15,NA,NA,NA,NA)
eastafrica.20 <- subset(eastafrica,eastafrica$Age >= 13 & eastafrica$Age < 15)
boot.eastafrica.20 <- boot(data=eastafrica.20,statistic=maxbrach,R=10000)
boot.eastafrica.20cis <- boot.ci(boot.eastafrica.20,type="bca")
eastafrica.boot20.stats <- c(14,max(boot.eastafrica.20$t),mean(boot.eastafrica.20$t),boot.eastafrica.20cis$bca[4],boot.eastafrica.20cis$bca[5])
eastafrica.21 <- subset(eastafrica,eastafrica$Age >= 12 & eastafrica$Age < 14)
boot.eastafrica.21 <- boot(data=eastafrica.21,statistic=maxbrach,R=10000)
boot.eastafrica.21cis <- boot.ci(boot.eastafrica.21,type="bca")
eastafrica.boot21.stats <- c(13,max(boot.eastafrica.21$t),mean(boot.eastafrica.21$t),boot.eastafrica.21cis$bca[4],boot.eastafrica.21cis$bca[5])
eastafrica.22 <- subset(eastafrica,eastafrica$Age >= 11 & eastafrica$Age < 13)
boot.eastafrica.22 <- boot(data=eastafrica.22,statistic=maxbrach,R=10000)
boot.eastafrica.22cis <- boot.ci(boot.eastafrica.22,type="bca")
eastafrica.boot22.stats <- c(12,max(boot.eastafrica.22$t),mean(boot.eastafrica.22$t),boot.eastafrica.22cis$bca[4],boot.eastafrica.22cis$bca[5])
eastafrica.23 <- subset(eastafrica,eastafrica$Age >= 10 & eastafrica$Age < 12)
boot.eastafrica.23 <- boot(data=eastafrica.23,statistic=maxbrach,R=10000)
boot.eastafrica.23cis <- boot.ci(boot.eastafrica.23,type="bca")
eastafrica.boot23.stats <- c(11,max(boot.eastafrica.23$t),mean(boot.eastafrica.23$t),3,3)
eastafrica.24 <- subset(eastafrica,eastafrica$Age >= 9 & eastafrica$Age < 11)
boot.eastafrica.24 <- boot(data=eastafrica.24,statistic=maxbrach,R=10000)
boot.eastafrica.24cis <- boot.ci(boot.eastafrica.24,type="bca")
eastafrica.boot24.stats <- c(10,max(boot.eastafrica.24$t),mean(boot.eastafrica.24$t),boot.eastafrica.24cis$bca[4],boot.eastafrica.24cis$bca[5])
eastafrica.25 <- subset(eastafrica,eastafrica$Age >= 8 & eastafrica$Age < 10)
boot.eastafrica.25 <- boot(data=eastafrica.25,statistic=maxbrach,R=10000)
boot.eastafrica.25cis <- boot.ci(boot.eastafrica.25,type="bca")
eastafrica.boot25.stats <- c(9,max(boot.eastafrica.25$t),mean(boot.eastafrica.25$t),boot.eastafrica.25cis$bca[4],boot.eastafrica.25cis$bca[5])
eastafrica.26 <- subset(eastafrica,eastafrica$Age >= 7 & eastafrica$Age < 9)
boot.eastafrica.26 <- boot(data=eastafrica.26,statistic=maxbrach,R=10000)
boot.eastafrica.26cis <- boot.ci(boot.eastafrica.26,type="bca")
eastafrica.boot26.stats <- c(8,max(boot.eastafrica.26$t),mean(boot.eastafrica.26$t),4,4)
eastafrica.27 <- subset(eastafrica,eastafrica$Age >= 6 & eastafrica$Age < 8)
boot.eastafrica.27 <- boot(data=eastafrica.27,statistic=maxbrach,R=10000)
boot.eastafrica.27cis <- boot.ci(boot.eastafrica.27,type="bca")
eastafrica.boot27.stats <- c(7,max(boot.eastafrica.27$t),mean(boot.eastafrica.27$t),boot.eastafrica.27cis$bca[4],boot.eastafrica.27cis$bca[5])
eastafrica.28 <- subset(eastafrica,eastafrica$Age >= 5 & eastafrica$Age < 7)
boot.eastafrica.28 <- boot(data=eastafrica.28,statistic=maxbrach,R=10000)
boot.eastafrica.28cis <- boot.ci(boot.eastafrica.28,type="bca")
eastafrica.boot28.stats <- c(6,max(boot.eastafrica.28$t),mean(boot.eastafrica.28$t),boot.eastafrica.28cis$bca[4],boot.eastafrica.28cis$bca[5])
eastafrica.29 <- subset(eastafrica,eastafrica$Age >= 4 & eastafrica$Age < 6)
boot.eastafrica.29 <- boot(data=eastafrica.29,statistic=maxbrach,R=10000)
boot.eastafrica.29cis <- boot.ci(boot.eastafrica.29,type="bca")
eastafrica.boot29.stats <- c(5,max(boot.eastafrica.29$t),mean(boot.eastafrica.29$t),boot.eastafrica.29cis$bca[4],boot.eastafrica.29cis$bca[5])
eastafrica.30 <- subset(eastafrica,eastafrica$Age >= 3 & eastafrica$Age < 5)
boot.eastafrica.30 <- boot(data=eastafrica.30,statistic=maxbrach,R=10000)
boot.eastafrica.30cis <- boot.ci(boot.eastafrica.30,type="bca")
eastafrica.boot30.stats <- c(4,max(boot.eastafrica.30$t),mean(boot.eastafrica.30$t),boot.eastafrica.30cis$bca[4],5)
eastafrica.31 <- subset(eastafrica,eastafrica$Age >= 2 & eastafrica$Age < 4)
boot.eastafrica.31 <- boot(data=eastafrica.31,statistic=maxbrach,R=10000)
boot.eastafrica.31cis <- boot.ci(boot.eastafrica.31,type="bca")
eastafrica.boot31.stats <- c(3,max(boot.eastafrica.31$t),mean(boot.eastafrica.31$t),boot.eastafrica.31cis$bca[4],5)
eastafrica.32 <- subset(eastafrica,eastafrica$Age >= 1 & eastafrica$Age < 3)
boot.eastafrica.32 <- boot(data=eastafrica.32,statistic=maxbrach,R=10000)
boot.eastafrica.32cis <- boot.ci(boot.eastafrica.32,type="bca")
eastafrica.boot32.stats <- c(2,max(boot.eastafrica.32$t),mean(boot.eastafrica.32$t),boot.eastafrica.32cis$bca[4],2)
eastafrica.33 <- subset(eastafrica,eastafrica$Age >= 0 & eastafrica$Age < 2)
boot.eastafrica.33 <- boot(data=eastafrica.33,statistic=maxbrach,R=10000)
boot.eastafrica.33cis <- boot.ci(boot.eastafrica.33,type="bca")
eastafrica.boot33.stats <- c(1,max(boot.eastafrica.33$t),mean(boot.eastafrica.33$t),boot.eastafrica.33cis$bca[4],boot.eastafrica.33cis$bca[5])

eastafrica.bootstraps <- rbind(eastafrica.boot5.stats,eastafrica.boot6.stats,eastafrica.boot7.stats,eastafrica.boot8.stats,eastafrica.boot9.stats,
                               eastafrica.boot10.stats,eastafrica.boot11.stats,eastafrica.boot12.stats,eastafrica.boot13.stats,eastafrica.boot14.stats,
                               eastafrica.boot15.stats,eastafrica.boot16.stats,eastafrica.boot17.stats,eastafrica.boot18.stats,eastafrica.boot19.stats,eastafrica.boot20.stats,eastafrica.boot21.stats,
                               eastafrica.boot22.stats,eastafrica.boot23.stats,eastafrica.boot24.stats,eastafrica.boot25.stats,eastafrica.boot26.stats,eastafrica.boot27.stats,eastafrica.boot28.stats,
                               eastafrica.boot29.stats,eastafrica.boot30.stats,eastafrica.boot31.stats,eastafrica.boot32.stats,eastafrica.boot33.stats)
colnames(eastafrica.bootstraps) <- c("Age","Maximum","Mean","CImin","CImax")
eastafrica.bootstraps <- as.data.frame(eastafrica.bootstraps)

eastafrica.boots.plot <- ggplot() + scale_x_reverse("Age (Ma)",limits=c(0,40)) + scale_y_continuous(name="Number of brachydonts",limits=c(0,20)) + 
  geom_errorbar(data = eastafrica.bootstraps,aes(x=Age,ymin=CImin,ymax=CImax),colour="black") +
  geom_point(data=eastafrica.bootstraps,aes(x=Age,y=Maximum),colour="black",size=2) +
  geom_point(data=eastafrica.bootstraps,aes(x=Age,y=Mean),colour="#118036",size=2) +
  theme_bw() + coord_geo(pos = list("bottom"), dat = list("epochs"),abbrv = FALSE, expand=TRUE) + theme(text=element_text(size=20))
eastafrica.boots.plot

#North America
usa.1 <- subset(usa.points,usa.points$midpoint >= 32 & usa.points$midpoint < 34)
boot.usa.1 <- boot(data=usa.1,statistic=maxbrach,R=10000)
boot.usa.1cis <- boot.ci(boot.usa.1,type="bca")
usa.boot1.stats <- c(33,max(boot.usa.1$t),mean(boot.usa.1$t),boot.usa.1cis$bca[4],boot.usa.1cis$bca[5])
usa.2 <- subset(usa.points,usa.points$midpoint >= 31 & usa.points$midpoint < 33)
boot.usa.2 <- boot(data=usa.2,statistic=maxbrach,R=10000)
boot.usa.2cis <- boot.ci(boot.usa.2,type="bca")
usa.boot2.stats <- c(32,max(boot.usa.2$t),mean(boot.usa.2$t),boot.usa.2cis$bca[4],boot.usa.2cis$bca[5])
usa.3 <- subset(usa.points,usa.points$midpoint >= 30 & usa.points$midpoint < 32)
boot.usa.3 <- boot(data=usa.3,statistic=maxbrach,R=10000)
boot.usa.3cis <- boot.ci(boot.usa.3,type="bca")
usa.boot3.stats <- c(31,max(boot.usa.3$t),mean(boot.usa.3$t),boot.usa.3cis$bca[4],boot.usa.3cis$bca[5])
usa.4 <- subset(usa.points,usa.points$midpoint >= 29 & usa.points$midpoint < 31)
boot.usa.4 <- boot(data=usa.4,statistic=maxbrach,R=10000)
boot.usa.4cis <- boot.ci(boot.usa.4,type="bca")
usa.boot4.stats <- c(30,max(boot.usa.4$t),mean(boot.usa.4$t),boot.usa.4cis$bca[4],boot.usa.4cis$bca[5])
usa.5 <- subset(usa.points,usa.points$midpoint >= 28 & usa.points$midpoint < 30)
boot.usa.5 <- boot(data=usa.5,statistic=maxbrach,R=10000)
boot.usa.5cis <- boot.ci(boot.usa.5,type="bca")
usa.boot5.stats <- c(29,max(boot.usa.5$t),mean(boot.usa.5$t),boot.usa.5cis$bca[4],boot.usa.5cis$bca[5])
usa.6 <- subset(usa.points,usa.points$midpoint >= 27 & usa.points$midpoint < 29)
boot.usa.6 <- boot(data=usa.6,statistic=maxbrach,R=10000)
boot.usa.6cis <- boot.ci(boot.usa.6,type="bca")
usa.boot6.stats <- c(28,max(boot.usa.6$t),mean(boot.usa.6$t),boot.usa.6cis$bca[4],boot.usa.6cis$bca[5])
usa.7 <- subset(usa.points,usa.points$midpoint >= 26 & usa.points$midpoint < 28)
boot.usa.7 <- boot(data=usa.7,statistic=maxbrach,R=10000)
boot.usa.7cis <- boot.ci(boot.usa.7,type="bca")
usa.boot7.stats <- c(27,max(boot.usa.7$t),mean(boot.usa.7$t),6,6)
usa.8 <- subset(usa.points,usa.points$midpoint >= 25 & usa.points$midpoint < 27)
boot.usa.8 <- boot(data=usa.8,statistic=maxbrach,R=10000)
boot.usa.8cis <- boot.ci(boot.usa.8,type="bca")
usa.boot8.stats <- c(26,max(boot.usa.8$t),mean(boot.usa.8$t),8,8)
usa.9 <- subset(usa.points,usa.points$midpoint >= 24 & usa.points$midpoint < 26)
boot.usa.9 <- boot(data=usa.9,statistic=maxbrach,R=10000)
boot.usa.9cis <- boot.ci(boot.usa.9,type="bca")
usa.boot9.stats <- c(25,max(boot.usa.9$t),mean(boot.usa.9$t),8,8)
usa.boot10.stats <- c(24,NA,NA,NA,NA)
usa.boot11.stats <- c(23,NA,NA,NA,NA)
usa.12 <- subset(usa.points,usa.points$midpoint >= 21 & usa.points$midpoint < 23)
boot.usa.12 <- boot(data=usa.12,statistic=maxbrach,R=10000)
boot.usa.12cis <- boot.ci(boot.usa.12,type="bca")
usa.boot12.stats <- c(22,max(boot.usa.12$t),mean(boot.usa.12$t),9,9)
usa.13 <- subset(usa.points,usa.points$midpoint >= 20 & usa.points$midpoint < 22)
boot.usa.13 <- boot(data=usa.13,statistic=maxbrach,R=10000)
boot.usa.13cis <- boot.ci(boot.usa.13,type="bca")
usa.boot13.stats <- c(21,max(boot.usa.13$t),mean(boot.usa.13$t),9,9)
usa.14 <- subset(usa.points,usa.points$midpoint >= 19 & usa.points$midpoint < 21)
boot.usa.14 <- boot(data=usa.14,statistic=maxbrach,R=10000)
boot.usa.14cis <- boot.ci(boot.usa.14,type="bca")
usa.boot14.stats <- c(20,max(boot.usa.14$t),mean(boot.usa.14$t),boot.usa.14cis$bca[4],boot.usa.14cis$bca[5])
usa.15 <- subset(usa.points,usa.points$midpoint >= 18 & usa.points$midpoint < 20)
boot.usa.15 <- boot(data=usa.15,statistic=maxbrach,R=10000)
boot.usa.15cis <- boot.ci(boot.usa.15,type="bca")
usa.boot15.stats <- c(19,max(boot.usa.15$t),mean(boot.usa.15$t),boot.usa.15cis$bca[4],boot.usa.15cis$bca[5])
usa.16 <- subset(usa.points,usa.points$midpoint >= 17 & usa.points$midpoint < 19)
boot.usa.16 <- boot(data=usa.16,statistic=maxbrach,R=10000)
boot.usa.16cis <- boot.ci(boot.usa.16,type="bca")
usa.boot16.stats <- c(18,max(boot.usa.16$t),mean(boot.usa.16$t),boot.usa.16cis$bca[4],boot.usa.16cis$bca[5])
usa.17 <- subset(usa.points,usa.points$midpoint >= 16 & usa.points$midpoint < 18)
boot.usa.17 <- boot(data=usa.17,statistic=maxbrach,R=10000)
boot.usa.17cis <- boot.ci(boot.usa.17,type="bca")
usa.boot17.stats <- c(17,max(boot.usa.17$t),mean(boot.usa.17$t),boot.usa.17cis$bca[4],boot.usa.17cis$bca[5])
usa.18 <- subset(usa.points,usa.points$midpoint >= 15 & usa.points$midpoint < 17)
boot.usa.18 <- boot(data=usa.18,statistic=maxbrach,R=10000)
boot.usa.18cis <- boot.ci(boot.usa.18,type="bca")
usa.boot18.stats <- c(16,max(boot.usa.18$t),mean(boot.usa.18$t),boot.usa.18cis$bca[4],boot.usa.18cis$bca[5])
usa.19 <- subset(usa.points,usa.points$midpoint >= 14 & usa.points$midpoint < 16)
boot.usa.19 <- boot(data=usa.19,statistic=maxbrach,R=10000)
boot.usa.19cis <- boot.ci(boot.usa.19,type="bca")
usa.boot19.stats <- c(15,max(boot.usa.19$t),mean(boot.usa.19$t),boot.usa.19cis$bca[4],boot.usa.19cis$bca[5])
usa.20 <- subset(usa.points,usa.points$midpoint >= 13 & usa.points$midpoint < 15)
boot.usa.20 <- boot(data=usa.20,statistic=maxbrach,R=10000)
boot.usa.20cis <- boot.ci(boot.usa.20,type="bca")
usa.boot20.stats <- c(14,max(boot.usa.20$t),mean(boot.usa.20$t),boot.usa.20cis$bca[4],boot.usa.20cis$bca[5])
usa.21 <- subset(usa.points,usa.points$midpoint >= 12 & usa.points$midpoint < 14)
boot.usa.21 <- boot(data=usa.21,statistic=maxbrach,R=10000)
boot.usa.21cis <- boot.ci(boot.usa.21,type="bca")
usa.boot21.stats <- c(13,max(boot.usa.21$t),mean(boot.usa.21$t),boot.usa.21cis$bca[4],boot.usa.21cis$bca[5])
usa.22 <- subset(usa.points,usa.points$midpoint >= 11 & usa.points$midpoint < 13)
boot.usa.22 <- boot(data=usa.22,statistic=maxbrach,R=10000)
boot.usa.22cis <- boot.ci(boot.usa.22,type="bca")
usa.boot22.stats <- c(12,max(boot.usa.22$t),mean(boot.usa.22$t),boot.usa.22cis$bca[4],boot.usa.22cis$bca[5])
usa.23 <- subset(usa.points,usa.points$midpoint >= 10 & usa.points$midpoint < 12)
boot.usa.23 <- boot(data=usa.23,statistic=maxbrach,R=10000)
boot.usa.23cis <- boot.ci(boot.usa.23,type="bca")
usa.boot23.stats <- c(11,max(boot.usa.23$t),mean(boot.usa.23$t),boot.usa.23cis$bca[4],boot.usa.23cis$bca[5])
usa.24 <- subset(usa.points,usa.points$midpoint >= 9 & usa.points$midpoint < 11)
boot.usa.24 <- boot(data=usa.24,statistic=maxbrach,R=10000)
boot.usa.24cis <- boot.ci(boot.usa.24,type="bca")
usa.boot24.stats <- c(10,max(boot.usa.24$t),mean(boot.usa.24$t),boot.usa.24cis$bca[4],boot.usa.24cis$bca[5])
usa.25 <- subset(usa.points,usa.points$midpoint >= 8 & usa.points$midpoint < 10)
boot.usa.25 <- boot(data=usa.25,statistic=maxbrach,R=10000)
boot.usa.25cis <- boot.ci(boot.usa.25,type="bca")
usa.boot25.stats <- c(9,max(boot.usa.25$t),mean(boot.usa.25$t),boot.usa.25cis$bca[4],boot.usa.25cis$bca[5])
usa.26 <- subset(usa.points,usa.points$midpoint >= 7 & usa.points$midpoint < 9)
boot.usa.26 <- boot(data=usa.26,statistic=maxbrach,R=10000)
boot.usa.26cis <- boot.ci(boot.usa.26,type="bca")
usa.boot26.stats <- c(8,max(boot.usa.26$t),mean(boot.usa.26$t),boot.usa.26cis$bca[4],boot.usa.26cis$bca[5])
usa.27 <- subset(usa.points,usa.points$midpoint >= 6 & usa.points$midpoint < 8)
boot.usa.27 <- boot(data=usa.27,statistic=maxbrach,R=10000)
boot.usa.27cis <- boot.ci(boot.usa.27,type="bca")
usa.boot27.stats <- c(7,max(boot.usa.27$t),mean(boot.usa.27$t),boot.usa.27cis$bca[4],boot.usa.27cis$bca[5])
usa.28 <- subset(usa.points,usa.points$midpoint >= 5 & usa.points$midpoint < 7)
boot.usa.28 <- boot(data=usa.28,statistic=maxbrach,R=10000)
boot.usa.28cis <- boot.ci(boot.usa.28,type="bca")
usa.boot28.stats <- c(6,max(boot.usa.28$t),mean(boot.usa.28$t),boot.usa.28cis$bca[4],boot.usa.28cis$bca[5])
usa.29 <- subset(usa.points,usa.points$midpoint >= 4 & usa.points$midpoint < 6)
boot.usa.29 <- boot(data=usa.29,statistic=maxbrach,R=10000)
boot.usa.29cis <- boot.ci(boot.usa.29,type="bca")
usa.boot29.stats <- c(5,max(boot.usa.29$t),mean(boot.usa.29$t),boot.usa.29cis$bca[4],boot.usa.29cis$bca[5])
usa.30 <- subset(usa.points,usa.points$midpoint >= 3 & usa.points$midpoint < 5)
boot.usa.30 <- boot(data=usa.30,statistic=maxbrach,R=10000)
boot.usa.30cis <- boot.ci(boot.usa.30,type="bca")
usa.boot30.stats <- c(4,max(boot.usa.30$t),mean(boot.usa.30$t),boot.usa.30cis$bca[4],boot.usa.30cis$bca[5])
usa.31 <- subset(usa.points,usa.points$midpoint >= 2 & usa.points$midpoint < 4)
boot.usa.31 <- boot(data=usa.31,statistic=maxbrach,R=10000)
boot.usa.31cis <- boot.ci(boot.usa.31,type="bca")
usa.boot31.stats <- c(3,max(boot.usa.31$t),mean(boot.usa.31$t),boot.usa.31cis$bca[4],boot.usa.31cis$bca[5])
usa.32 <- subset(usa.points,usa.points$midpoint >= 1 & usa.points$midpoint < 3)
boot.usa.32 <- boot(data=usa.32,statistic=maxbrach,R=10000)
boot.usa.32cis <- boot.ci(boot.usa.32,type="bca")
usa.boot32.stats <- c(2,max(boot.usa.32$t),mean(boot.usa.32$t),boot.usa.32cis$bca[4],boot.usa.32cis$bca[5])
usa.33 <- subset(usa.points,usa.points$midpoint >= 35 & usa.points$midpoint < 37)
boot.usa.33 <- boot(data=usa.33,statistic=maxbrach,R=10000)
boot.usa.33cis <- boot.ci(boot.usa.33,type="bca")
usa.boot33.stats <- c(36,max(boot.usa.33$t),mean(boot.usa.33$t),13,13)
usa.34 <- subset(usa.points,usa.points$midpoint >= 34 & usa.points$midpoint < 36)
boot.usa.34 <- boot(data=usa.34,statistic=maxbrach,R=10000)
boot.usa.34cis <- boot.ci(boot.usa.33,type="bca")
usa.boot34.stats <- c(35,max(boot.usa.33$t),mean(boot.usa.33$t),13,13)

usa.bootstraps <- rbind(usa.boot33.stats,usa.boot34.stats,usa.boot1.stats,usa.boot2.stats,usa.boot3.stats,usa.boot4.stats,usa.boot5.stats,usa.boot6.stats,usa.boot7.stats,
                        usa.boot8.stats,usa.boot9.stats,usa.boot10.stats,usa.boot11.stats,usa.boot12.stats,usa.boot13.stats,usa.boot14.stats,
                        usa.boot15.stats,usa.boot16.stats,usa.boot17.stats,usa.boot18.stats,usa.boot19.stats,usa.boot20.stats,usa.boot21.stats,
                        usa.boot22.stats,usa.boot23.stats,usa.boot24.stats,usa.boot25.stats,usa.boot26.stats,usa.boot27.stats,usa.boot28.stats,
                        usa.boot29.stats,usa.boot30.stats,usa.boot31.stats,usa.boot32.stats)
colnames(usa.bootstraps) <- c("Age","Maximum","Mean","CImin","CImax")
usa.bootstraps <- as.data.frame(usa.bootstraps)

usa.boots.plot <- ggplot() + scale_x_reverse("Age (Ma)",limits=c(0,40)) + scale_y_continuous(name="Number of brachydonts",limits=c(0,20)) + 
  geom_errorbar(data = usa.bootstraps,aes(x=Age,ymin=CImin,ymax=CImax),colour="black") +
  geom_point(data=usa.bootstraps,aes(x=Age,y=Maximum),colour="black",size=2) +
  geom_point(data=usa.bootstraps,aes(x=Age,y=Mean),colour="#e87400",size=2) +
  theme_bw() + coord_geo(pos = list("bottom"), dat = list("epochs"),abbrv = FALSE, expand=TRUE) + theme(text=element_text(size=20))
usa.boots.plot

all.regions.boots <- ggarrange(europe.boots.plot,balkanotolia.boots.plot,centralasia.boots.plot,india.boots.plot,eastafrica.boots.plot,usa.boots.plot,nrow=2,ncol=3)
all.regions.boots
ggsave(filename = "Bootstrapping results by region.svg", plot = all.regions.boots, width = 14, height = 10, units = 'cm', scale = 2, dpi = 800)

#South America
#Separate function for South America because non-hypsodonts are used rather than brachydonts
maxbrachsa <- function(data, indices){
  d <- data[indices,] # allows boot to select sample
  fit <- max(d$nnonHYP)
  return(fit)
} 

sa.1 <- subset(southam,southam$Age >= 32 & southam$Age < 34)
boot.sa.1 <- boot(data=sa.1,statistic=maxbrachsa,R=10000)
boot.sa.1cis <- boot.ci(boot.sa.1,type="bca")
sa.boot1.stats <- c(33,max(boot.sa.1$t),mean(boot.sa.1$t),boot.sa.1cis$bca[4],boot.sa.1cis$bca[5])
sa.2 <- subset(southam,southam$Age >= 31 & southam$Age < 33)
boot.sa.2 <- boot(data=sa.2,statistic=maxbrachsa,R=10000)
boot.sa.2cis <- boot.ci(boot.sa.2,type="bca")
sa.boot2.stats <- c(32,max(boot.sa.2$t),mean(boot.sa.2$t),boot.sa.2cis$bca[4],boot.sa.2cis$bca[5])
sa.3 <- subset(southam,southam$Age >= 30 & southam$Age < 32)
boot.sa.3 <- boot(data=sa.3,statistic=maxbrachsa,R=10000)
boot.sa.3cis <- boot.ci(boot.sa.3,type="bca")
sa.boot3.stats <- c(31,max(boot.sa.3$t),mean(boot.sa.3$t),boot.sa.3cis$bca[4],boot.sa.3cis$bca[5])
sa.4 <- subset(southam,southam$Age >= 29 & southam$Age < 31)
boot.sa.4 <- boot(data=sa.4,statistic=maxbrachsa,R=10000)
boot.sa.4cis <- boot.ci(boot.sa.4,type="bca")
sa.boot4.stats <- c(30,max(boot.sa.4$t),mean(boot.sa.4$t),boot.sa.4cis$bca[4],boot.sa.4cis$bca[5])
sa.boot5.stats <- c(29,NA,NA,NA,NA)
sa.boot6.stats <- c(28,NA,NA,NA,NA)
sa.7 <- subset(southam,southam$Age >= 26 & southam$Age < 28)
boot.sa.7 <- boot(data=sa.7,statistic=maxbrachsa,R=10000)
boot.sa.7cis <- boot.ci(boot.sa.7,type="bca")
sa.boot7.stats <- c(27,max(boot.sa.7$t),mean(boot.sa.7$t),boot.sa.7cis$bca[4],boot.sa.7cis$bca[5])
sa.8 <- subset(southam,southam$Age >= 25 & southam$Age < 27)
boot.sa.8 <- boot(data=sa.8,statistic=maxbrachsa,R=10000)
boot.sa.8cis <- boot.ci(boot.sa.8,type="bca")
sa.boot8.stats <- c(26,max(boot.sa.8$t),mean(boot.sa.8$t),boot.sa.8cis$bca[4],boot.sa.8cis$bca[5])
sa.9 <- subset(southam,southam$Age >= 24 & southam$Age < 26)
boot.sa.9 <- boot(data=sa.9,statistic=maxbrachsa,R=10000)
boot.sa.9cis <- boot.ci(boot.sa.9,type="bca")
sa.boot9.stats <- c(25,max(boot.sa.9$t),mean(boot.sa.9$t),boot.sa.9cis$bca[4],boot.sa.9cis$bca[5])
sa.10 <- subset(southam,southam$Age >= 23 & southam$Age < 25)
boot.sa.10 <- boot(data=sa.10,statistic=maxbrachsa,R=10000)
boot.sa.10cis <- boot.ci(boot.sa.10,type="bca")
sa.boot10.stats <- c(24,max(boot.sa.10$t),mean(boot.sa.10$t),boot.sa.10cis$bca[4],boot.sa.10cis$bca[5])
sa.boot11.stats <- c(23,NA,NA,NA,NA)
sa.boot12.stats <- c(22,NA,NA,NA,NA)
sa.13 <- subset(southam,southam$Age >= 20 & southam$Age < 22)
boot.sa.13 <- boot(data=sa.13,statistic=maxbrachsa,R=10000)
boot.sa.13cis <- boot.ci(boot.sa.13,type="bca")
sa.boot13.stats <- c(21,max(boot.sa.13$t),mean(boot.sa.13$t),boot.sa.13cis$bca[4],boot.sa.13cis$bca[5])
sa.14 <- subset(southam,southam$Age >= 19 & southam$Age < 21)
boot.sa.14 <- boot(data=sa.14,statistic=maxbrachsa,R=10000)
boot.sa.14cis <- boot.ci(boot.sa.14,type="bca")
sa.boot14.stats <- c(20,max(boot.sa.14$t),mean(boot.sa.14$t),boot.sa.14cis$bca[4],boot.sa.14cis$bca[5])
sa.15 <- subset(southam,southam$Age >= 18 & southam$Age < 20)
boot.sa.15 <- boot(data=sa.15,statistic=maxbrachsa,R=10000)
boot.sa.15cis <- boot.ci(boot.sa.15,type="bca")
sa.boot15.stats <- c(19,max(boot.sa.15$t),mean(boot.sa.15$t),boot.sa.15cis$bca[4],boot.sa.15cis$bca[5])
sa.16 <- subset(southam,southam$Age >= 17 & southam$Age < 19)
boot.sa.16 <- boot(data=sa.16,statistic=maxbrachsa,R=10000)
boot.sa.16cis <- boot.ci(boot.sa.16,type="bca")
sa.boot16.stats <- c(18,max(boot.sa.16$t),mean(boot.sa.16$t),boot.sa.16cis$bca[4],boot.sa.16cis$bca[5])
sa.17 <- subset(southam,southam$Age >= 16 & southam$Age < 18)
boot.sa.17 <- boot(data=sa.17,statistic=maxbrachsa,R=10000)
boot.sa.17cis <- boot.ci(boot.sa.17,type="bca")
sa.boot17.stats <- c(17,max(boot.sa.17$t),mean(boot.sa.17$t),boot.sa.17cis$bca[4],boot.sa.17cis$bca[5])
sa.18 <- subset(southam,southam$Age >= 15 & southam$Age < 17)
boot.sa.18 <- boot(data=sa.18,statistic=maxbrachsa,R=10000)
boot.sa.18cis <- boot.ci(boot.sa.18,type="bca")
sa.boot18.stats <- c(16,max(boot.sa.18$t),mean(boot.sa.18$t),boot.sa.18cis$bca[4],boot.sa.18cis$bca[5])
sa.19 <- subset(southam,southam$Age >= 14 & southam$Age < 16)
boot.sa.19 <- boot(data=sa.19,statistic=maxbrachsa,R=10000)
boot.sa.19cis <- boot.ci(boot.sa.19,type="bca")
sa.boot19.stats <- c(15,max(boot.sa.19$t),mean(boot.sa.19$t),boot.sa.19cis$bca[4],boot.sa.19cis$bca[5])
sa.20 <- subset(southam,southam$Age >= 13 & southam$Age < 15)
boot.sa.20 <- boot(data=sa.20,statistic=maxbrachsa,R=10000)
boot.sa.20cis <- boot.ci(boot.sa.20,type="bca")
sa.boot20.stats <- c(14,max(boot.sa.20$t),mean(boot.sa.20$t),boot.sa.20cis$bca[4],boot.sa.20cis$bca[5])
sa.21 <- subset(southam,southam$Age >= 12 & southam$Age < 14)
boot.sa.21 <- boot(data=sa.21,statistic=maxbrachsa,R=10000)
boot.sa.21cis <- boot.ci(boot.sa.21,type="bca")
sa.boot21.stats <- c(13,max(boot.sa.21$t),mean(boot.sa.21$t),boot.sa.21cis$bca[4],boot.sa.21cis$bca[5])
sa.22 <- subset(southam,southam$Age >= 11 & southam$Age < 13)
boot.sa.22 <- boot(data=sa.22,statistic=maxbrachsa,R=10000)
boot.sa.22cis <- boot.ci(boot.sa.22,type="bca")
sa.boot22.stats <- c(12,max(boot.sa.22$t),mean(boot.sa.22$t),boot.sa.22cis$bca[4],boot.sa.22cis$bca[5])
sa.23 <- subset(southam,southam$Age >= 10 & southam$Age < 12)
boot.sa.23 <- boot(data=sa.23,statistic=maxbrachsa,R=10000)
boot.sa.23cis <- boot.ci(boot.sa.23,type="bca")
sa.boot23.stats <- c(11,max(boot.sa.23$t),mean(boot.sa.23$t),boot.sa.23cis$bca[4],boot.sa.23cis$bca[5])
sa.24 <- subset(southam,southam$Age >= 9 & southam$Age < 11)
boot.sa.24 <- boot(data=sa.24,statistic=maxbrachsa,R=10000)
boot.sa.24cis <- boot.ci(boot.sa.24,type="bca")
sa.boot24.stats <- c(10,max(boot.sa.24$t),mean(boot.sa.24$t),boot.sa.24cis$bca[4],boot.sa.24cis$bca[5])
sa.25 <- subset(southam,southam$Age >= 8 & southam$Age < 10)
boot.sa.25 <- boot(data=sa.25,statistic=maxbrachsa,R=10000)
boot.sa.25cis <- boot.ci(boot.sa.25,type="bca")
sa.boot25.stats <- c(9,max(boot.sa.25$t),mean(boot.sa.25$t),boot.sa.25cis$bca[4],boot.sa.25cis$bca[5])
sa.26 <- subset(southam,southam$Age >= 7 & southam$Age < 9)
boot.sa.26 <- boot(data=sa.26,statistic=maxbrachsa,R=10000)
boot.sa.26cis <- boot.ci(boot.sa.26,type="bca")
sa.boot26.stats <- c(8,max(boot.sa.26$t),mean(boot.sa.26$t),boot.sa.26cis$bca[4],boot.sa.26cis$bca[5])
sa.27 <- subset(southam,southam$Age >= 6 & southam$Age < 8)
boot.sa.27 <- boot(data=sa.27,statistic=maxbrachsa,R=10000)
boot.sa.27cis <- boot.ci(boot.sa.27,type="bca")
sa.boot27.stats <- c(7,max(boot.sa.27$t),mean(boot.sa.27$t),boot.sa.27cis$bca[4],boot.sa.27cis$bca[5])
sa.28 <- subset(southam,southam$Age >= 5 & southam$Age < 7)
boot.sa.28 <- boot(data=sa.28,statistic=maxbrachsa,R=10000)
boot.sa.28cis <- boot.ci(boot.sa.28,type="bca")
sa.boot28.stats <- c(6,max(boot.sa.28$t),mean(boot.sa.28$t),boot.sa.28cis$bca[4],boot.sa.28cis$bca[5])
sa.29 <- subset(southam,southam$Age >= 4 & southam$Age < 6)
boot.sa.29 <- boot(data=sa.29,statistic=maxbrachsa,R=10000)
boot.sa.29cis <- boot.ci(boot.sa.29,type="bca")
sa.boot29.stats <- c(5,max(boot.sa.29$t),mean(boot.sa.29$t),boot.sa.29cis$bca[4],boot.sa.29cis$bca[5])
sa.30 <- subset(southam,southam$Age >= 3 & southam$Age < 5)
boot.sa.30 <- boot(data=sa.30,statistic=maxbrachsa,R=10000)
boot.sa.30cis <- boot.ci(boot.sa.30,type="bca")
sa.boot30.stats <- c(4,max(boot.sa.30$t),mean(boot.sa.30$t),boot.sa.30cis$bca[4],boot.sa.30cis$bca[5])
sa.31 <- subset(southam,southam$Age >= 2 & southam$Age < 4)
boot.sa.31 <- boot(data=sa.31,statistic=maxbrachsa,R=10000)
boot.sa.31cis <- boot.ci(boot.sa.31,type="bca")
sa.boot31.stats <- c(3,max(boot.sa.31$t),mean(boot.sa.31$t),boot.sa.31cis$bca[4],boot.sa.31cis$bca[5])
sa.32 <- subset(southam,southam$Age >= 1 & southam$Age < 3)
boot.sa.32 <- boot(data=sa.32,statistic=maxbrachsa,R=10000)
boot.sa.32cis <- boot.ci(boot.sa.32,type="bca")
sa.boot32.stats <- c(2,max(boot.sa.32$t),mean(boot.sa.32$t),boot.sa.32cis$bca[4],boot.sa.32cis$bca[5])
sa.33 <- subset(southam,southam$Age >= 0 & southam$Age < 2)
boot.sa.33 <- boot(data=sa.33,statistic=maxbrachsa,R=10000)
boot.sa.33cis <- boot.ci(boot.sa.33,type="bca")
sa.boot33.stats <- c(1,max(boot.sa.33$t),mean(boot.sa.33$t),boot.sa.33cis$bca[4],boot.sa.33cis$bca[5])

nnonHYP.bootstraps <- rbind(sa.boot1.stats,sa.boot2.stats,sa.boot3.stats,sa.boot4.stats,sa.boot5.stats,sa.boot6.stats,sa.boot7.stats,
                            sa.boot8.stats,sa.boot9.stats,sa.boot10.stats,sa.boot11.stats,sa.boot12.stats,sa.boot13.stats,sa.boot14.stats,
                            sa.boot15.stats,sa.boot16.stats,sa.boot17.stats,sa.boot18.stats,sa.boot19.stats,sa.boot20.stats,sa.boot21.stats,
                            sa.boot22.stats,sa.boot23.stats,sa.boot24.stats,sa.boot25.stats,sa.boot26.stats,sa.boot27.stats,sa.boot28.stats,
                            sa.boot29.stats,sa.boot30.stats,sa.boot31.stats)
colnames(nnonHYP.bootstraps) <- c("Age","Maximum","Mean","CImin","CImax")

sa.brachydont.time.bootstraps.plot <- ggplot() + scale_x_reverse("Age (Ma)") + scale_y_continuous(name="Non-hypsodont species") + 
  geom_errorbar(data = nnonHYP.bootstraps,aes(x=Age,ymin=CImin,ymax=CImax),colour="black") +
  geom_point(data=nnonHYP.bootstraps,aes(x=Age,y=Maximum),colour="black",size=2) +
  geom_point(data=nnonHYP.bootstraps,aes(x=Age,y=Mean),colour="#f8be00",size=2) +
  theme_bw() + coord_geo(pos = list("bottom"), dat = list("epochs"),abbrv = FALSE, expand=TRUE) + theme(text=element_text(size=20))
sa.brachydont.time.bootstraps.plot

#Autocorrelation tests
#Use maximum number of brachydonts through time in each region
#Convert bins into time series index
#Impute missing data (where present) using Kalman smoothing
europe.bindata <- europe.bootstraps$Maximum
ts.europe <- ts(europe.bindata,start=c(1,1),frequency=1)
Box.test(ts.europe,type="Ljung-Box")
balkanotolia.bindata <- balkanotolia.bootstraps$Maximum
ts.balkanotolia <- ts(balkanotolia.bindata,start=c(1,1),frequency=1)
ts.balkanotolia.x <- na_kalman(ts.balkanotolia)
Box.test(ts.balkanotolia.x,type="Ljung-Box")
centralasia.bindata <- centralasia.bootstraps$Maximum
ts.centralasia <- ts(centralasia.bindata,start=c(1,1),frequency=1)
ts.centralasia.x <- na_kalman(ts.centralasia)
Box.test(ts.centralasia.x,type="Ljung-Box")
india.bindata <- india.bootstraps$Maximum
ts.india <- ts(india.bindata,start=c(1,1),frequency=1)
ts.india.x <- na_kalman(ts.india)
Box.test(ts.india.x,type="Ljung-Box")
eastafrica.bindata <- eastafrica.bootstraps$Maximum
ts.eastafrica <- ts(eastafrica.bindata,start=c(1,1),frequency=1)
ts.eastafrica.x <- na_kalman(ts.eastafrica)
Box.test(ts.eastafrica.x,type="Ljung-Box")
usa.bindata <- usa.bootstraps$Maximum
ts.usa <- ts(usa.bindata,start=c(1,1),frequency=1)
ts.usa.x <- na_kalman(ts.usa)
Box.test(ts.usa.x,type="Ljung-Box")
sa.nonHYP.bindata <- nnonHYP.bootstraps$Maximum
ts.sa.nonHYP <- ts(sa.nonHYP.bindata,start=c(1,1),frequency=1)
ts.sa.nonHYP.x <- na_kalman(ts.sa.nonHYP)
Box.test(ts.sa.nonHYP.x,type="Ljung-Box")
